### ISSUE TITLE
Generating for v2 CS have errors

### ISSUE THREAD

**Issue by tuloski** [mavlink/mavlink#813] opened 2017-12-22 14:57 UTC
CS\common\ByteArrayUtils.cs could not be found 
CS\common\FrameworkBitConverter.cs could not be found 
CS\common\Mavlink.cs could not be found 

but I can find the files in the common folder, but they are only for v1, i.e. they expect the package with this anatomy
                * 0  Packet start sign	
                * 1	 Payload length	 0 - 255
                * 2	 Packet sequence	 0 - 255
                * 3	 System ID	 1 - 255
                * 4	 Component ID	 0 - 255
                * 5	 Message ID	 0 - 255
                * 6 to (n+6)	 Data	 (0 - 255) bytes
                * (n+7) to (n+8)	 Checksum (high byte, low byte) for v0.9, lowbyte, highbyte for 1.0
while v2 requires a different anatomy.

**Comment by amilcarlucas** [comment] 2018-02-20 12:37
@hamishwillee This is a duplicate of #482 and can be closed.

**Closed** 2018-02-20 22:04 UTC
