### ISSUE TITLE
Wireshark dissector AUTOPILOT_VERSION

### ISSUE THREAD

**Issue by dronevdl** [mavlink/mavlink#2105] opened 2024-04-24 15:01 UTC
Lua error is dissecting the AUTOPILOT_VERSION message.

Daily build of QGroundControl, CubeOrange with PX4.

Here is the screenshot of Wireshark:
![Screenshot from 2024-04-24 16-56-03](https://github.com/mavlink/mavlink/assets/161309275/45b23645-7241-4612-abc1-f915d2884ec5)

Here is a pcap file with one packet to reproduce the problem:
[autopilotversion.zip](https://github.com/mavlink/mavlink/files/15096338/autopilotversion.zip)

**Comment by hamishwillee** [comment] 2024-04-25 04:37
FYI @rotu @shancock884  - in case you can advise

**Comment by rotu** [comment] 2024-04-25 05:13
![image](https://github.com/mavlink/mavlink/assets/119948/9f2f2e49-7021-4466-b6c7-dcc835e5a234)

no such problem here.
Wireshark version 4.2.4
[mavlink-common.lua.zip](https://github.com/mavlink/mavlink/files/15104505/mavlink-common.lua.zip)

What version of Wireshark are you using? Can you upload your .lua?

**Comment by shancock884** [comment] 2024-04-25 06:49
This appears to be exactly the issue described in: https://github.com/ArduPilot/pymavlink/issues/852.
The issue is fixed in PR https://github.com/ArduPilot/pymavlink/pull/886, which was included in the 2.4.41 release of pymavlink (or any recent master branch).

**Comment by dronevdl** [comment] 2024-04-25 10:02
I am sorry, it works now.
I did a git clone a long time ago, did a git pull yesterday, but apparently that did not update everything.
I did  rm -rf and git clone today and now it works.
Wireshark 3.2.3 on Ubuntu 20.04.
This can be closed, sorry for the inconvenience.

**Comment by shancock884** [comment] 2024-04-25 10:44
No worries.... good that you are sorted.
It wont affect this, but for your info: on Ubuntu, the Wireshark version on the normal package repo is quite old, so if you want a more up-to-date version, you need to do: `sudo add-apt-repository ppa:wireshark-dev/stable` before installing or updating.

**Closed** 2024-04-25 11:23 UTC
