### ISSUE TITLE
mavlink_conversions.h compile issue

### ISSUE THREAD

**Issue by ssepa001** [mavlink/mavlink#627] opened 2016-09-29 20:38 UTC
So I am trying to compile a simple send program in Arduino but I get the following error with regards to the library : 

mavlink_conversions.h:38:1: error: 'MAVLINK_HELPER' does not name a type
\libraries\mavlink/mavlink_conversions.h:67: error: expected constructor, destructor, or type conversion before 'void'

Any ideas ?

**Comment by magicrub** [comment] 2016-09-29 22:57
Are you compiling via python?

**Comment by ssepa001** [comment] 2016-09-29 23:04
Yes

**Comment by amilcarlucas** [comment] 2018-02-19 14:40
please include just include one single file. For example minimal.h do not include common.h explicitly.

This is not a bug. IMHO This can be closed now

**Comment by hamishwillee** [comment] 2018-02-20 07:08
Thanks @amilcarlucas . Closing.

**Closed by hamishwillee** 2018-02-20 07:08 UTC
