### ISSUE TITLE
mavlink.io website offline

### ISSUE THREAD

**Issue by MaxBec** [mavlink/mavlink#1289] opened 2020-01-13 11:00 UTC
Hey guys,

the mavlink.io website seems to be offline. Can you confirm that?
![mavlink_io](https://user-images.githubusercontent.com/8254514/72250628-5017f700-35fc-11ea-91e2-77a1f77a45cb.png)

**Comment by hamishwillee** [comment] 2020-01-13 23:59
It is working for me now, from Australia.

**Comment by dayjaby** [comment] 2020-01-27 15:43
Still not working from Germany.

**Comment by hamishwillee** [comment] 2020-01-28 04:31
I can access the site through a German proxy server:

![image](https://user-images.githubusercontent.com/5368500/73235519-e9413300-41e2-11ea-8b60-1bf78f44f89c.png)

As I understand the Internet, that pretty much means that the problem is local to specific users, and not something we can deal with. I'm therefore closing - though happy for you to reopen if you can think of anything that we can do to further debug or help with this.

**Closed** 2020-01-28 04:31 UTC

**Comment by hamishwillee** [comment] 2020-01-28 04:32
And if needed, the content can be found here: https://github.com/mavlink/mavlink-devguide/tree/master/en

you can build locally by adapting the instructions here: http://dev.px4.io/master/en/contribute/docs.html#gitbook-documentation-toolchain - at least on Ubuntu.

**Comment by devurandom** [comment] 2020-02-15 06:27
```
❯ drill mavlink.io
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 43793
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; mavlink.io.  IN      A

;; ANSWER SECTION:
mavlink.io.     109     IN      CNAME   www.gitbooks.io.
www.gitbooks.io.        3409    IN      CNAME   cdn.gitbook.com.
```
