### ISSUE TITLE
How can i get the accurate longitude and latitude  to make a distinction between East or West ，North or South?

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/mavlink#710] opened 2017-04-20 06:57 UTC
I parse the #24  mavlink protocol to get longitude and latitude, but i can not know it it from East or West  ,North or South. Thanks

**Comment by amilcarlucas** [comment] 2018-02-19 14:34
Well, you get lat/and lon information, To convert it to a local reference frame you need a reference location.

There are other mavlink messages that provide you with that information.

AFAIK this is not a bug and can be closed now.

**Comment by hamishwillee** [comment] 2018-02-20 07:10
Closing. Best place for support is Slack: https://mavlink.io/en/#support

**Closed by hamishwillee** 2018-02-20 07:10 UTC
