### ISSUE TITLE
Wireshark mavlink_2_common.lua:9330: bad argument #1 to 'rshift' (number expected, got nil)

### ISSUE THREAD

**Issue by patrickpoirier51** [mavlink/mavlink#1978] opened 2023-04-25 14:36 UTC
Using LUA script i have this error trying to decode a HEARTBEAT message 
Lua Error: C:\Program Files\Wireshark\plugins\mavlink_2_common.lua:9330: bad argument #1 to 'rshift' (number expected, got nil)

![image](https://user-images.githubusercontent.com/12484190/234310612-a7b3807c-669e-4ae9-ad36-e3f25540c4c8.png)

Line 9330 is bold: 
-- dissect flag field
function dissect_flags_MAV_MODE_FLAG(tree, name, value)
    local bitval
    **bitval = bit.band(bit.rshift(value, 0), 1)**
    tree:add(f[name .. "_flagMAV_MODE_FLAG_CUSTOM_MODE_ENABLED"], bitval ~= 0, ".... ..." .. tostring(bitval) .. " MAV_MODE_FLAG_CUSTOM_MODE_ENABLED: " .. tostring(bitval ~= 0))

**Comment by hamishwillee** [comment] 2023-04-27 11:25
@peterbarker Anything you're familiar with?

**Comment by peterbarker** [comment] 2023-05-02 01:24
> @peterbarker Anything you're familiar with?

Nope!

I would query whether @patrickpoirier51 is running the "wireshark lua" or "just plain lua" bindings however.  They're different generators.

**Comment by patrickpoirier51** [comment] 2023-05-02 10:34
@peterbarker  I generated using the command in the wiki

python3 -m pymavlink.tools.mavgen --lang=WLua --wire-protocol=2.0 --output=mavlink_2_common message_definitions/v1.0/common.xml

**Comment by hamishwillee** [comment] 2023-05-03 07:50
@patrickpoirier51 Perhaps not very useful, but I can confirm I get the same error. This is using latest master on mavlink/mavlink and the command above. Flight stack PX4 running on WSL to QGC running on Windows.

I haven't seen that error before and it doesn't seem to be stopping me from looking at the packets.

@peterbarker Any thoughts on best person to ask about this. I can replicate on other flight stacks or whatever first if needed.

**Comment by patrickpoirier51** [comment] 2023-05-03 09:52
@hamishwillee  thanks for testing
It does have an impact on looking at packets as it does not provide details on Heartbeat payload as showned in picture.
Something has chaged in the message structure as it it expecting a value.... or this error has always been there ... ;-)

**Comment by hamishwillee** [comment] 2023-05-04 03:04
You're welcome. I don't know Lua so only so far I can take it myself, even though I think this is important.

I tried a bisection, but never found a version in which it worked. Got as far back in mavlink/mavlink as Nov 19, 2019 (commit 4bbdb628e075be463b3eb6a4529ca010d18cde9d) and HEARTBEAT always has this error.  NOt sure if that is "always", but definitely shows a lack of testing somewhere along the line. I guess in fairness, who tests HEARTBEAT :-)

This affects all messages, such as PAYLOAD_TARGET_LOCAL_NED, that need to dissect flags. Here, for example is the code for the heartbeat. The error is that the value passed in to dissect_flags_MAV_MODE_FLAG is `nil`.

```lua
    subtree, value = tree:add_le(f.HEARTBEAT_autopilot, padded(field_offset, 1))
    field_offset = offset + 6
    subtree, value = tree:add_le(f.HEARTBEAT_base_mode, padded(field_offset, 1))
    dissect_flags_MAV_MODE_FLAG(subtree, "HEARTBEAT_base_mode", value)
```

The code to get the offset is correct, so I logged all the values using a pattern like this:
```lua
    print("HEARTBEAT_base_mode: ", padded(field_offset, 1))
    print("val: ", value)
```

Those showed values for the first case, but not the second. So the problem here is that `value` returned from adding the leaf that is passed in to `dissect_flags_MAV_MODE_FLAG` is nil. This is the only place we use the returned value, which is why we aren't seen the error elsewhere (could tidy up the code to remove this return elsewhere).

NOTE, according to the docs, the value should be returned, so I do not know why it is coming back as nil. Maybe because it is "userdata" - see bleow.

Anyway, I modified this to:

```lua
    dissect_flags_MAV_MODE_FLAG(subtree, "HEARTBEAT_base_mode", padded(field_offset, 1))
```
Now I get an error that Lua thinks the passed in value is `userData`. Which it is - arbitrary data out of C.
However I'm not sure how to convert that into a number - I'm pretty sure you can cast from this to a number eventually, but my concern is that how you do this will depend on the endianness of the system and the size of the data.

So at this point we need someone who is a programmer. I can solve this, but it is not the best use of my time.

@peterbarker Can you suggest other options here? Lua experts we can ask. They will solve this much faster than me.

**Comment by peterbarker** [comment] 2023-05-04 03:24
> @peterbarker Can you suggest other options here? Lua experts we can ask. They will solve this much faster than me.


Well, there's always the option of pinging @rotu - the last committer to the file and this most likely to know what's going on :-)

**Comment by patrickpoirier51** [comment] 2023-05-04 10:23
@hamishwillee  thanks for all the effort You put into this.

**Comment by hamishwillee** [comment] 2023-05-04 21:47
@patrickpoirier51 You're welcome.  Wireshark is invaluable.

**Comment by hamishwillee** [comment] 2023-05-10 00:23
@rotu - would you be able to advise on this?

**Comment by hamishwillee** [comment] 2023-05-10 22:41
Howdy @patrickpoirier51 
I've cross-posted to https://github.com/ArduPilot/pymavlink/issues/815 where the generator issues are addressed - we'll try to get some more expertise there.

**Comment by rotu** [comment] 2023-05-10 23:01
I spent some time looking at this and my takeaway is that the author meant to write `TreeItem.add_packet_field` since I don't think that `TreeItem.add_le` returns the value. Trouble is, switching to `add_packet_field` causes an error:

> Expert Info (Error/Malformed): C:\gitlab-builds\builds\MsQ3pox2\1\wireshark\wireshark\epan\proto.c:4024: failed assertion "(guint)hfindex < gpa_hfinfo.len" (Unregistered hf!)

This might be why the author went with `add_le` in the first place.

I think the right fix anyway is to use boolean fields with a bit offset:
```lua
f.SomeBitFlags = ProtoField.new(name, abbr, type)
f.SomeBitFlag1 = ProtoField.bool("FLAG1", name, nbits, nil, 0x1, desc)
f.SomeBitFlag2 = ProtoField.bool("FLAG2", name, nbits, nil, 0x2, desc)

raw_field = padded(field_offset, 1)
subtree = tree:add_le(f.SomeBitFlags, raw_field)
subtree:add_le(f.SomeBitFlag1, raw_field)
subtree:add_le(f.SomeBitFlag2, raw_field)
```

**Comment by hamishwillee** [comment] 2023-05-11 00:31
Thanks @rotu - Would you be able to PR a fix at some point? I'm willing to try - but it's clearly far more "risky" than you doing it.

**Comment by rotu** [comment] 2023-05-11 01:11
> Thanks @rotu - Would you be able to PR a fix at some point? I'm willing to try - but it's clearly far more "risky" than you doing it.

I don’t have any lua skills to speak of and I don’t know what I’m doing. But I can take a crack at it.

**Comment by hamishwillee** [comment] 2023-05-18 00:15
@patrickpoirier51 The fix by @rotu in https://github.com/ArduPilot/pymavlink/pull/817 looks great to me, but I am not an expert. You might want to try it out though https://github.com/ArduPilot/pymavlink/pull/817 if you're stumped while we work on getting this in.

**Comment by patrickpoirier51** [comment] 2023-05-18 12:28
@hamishwillee 
 ok I will give it a try and report back
Thank You

**Comment by Davidbrcz** [comment] 2023-09-11 12:02
Any update on this ? It has bitten me lately.

**Comment by hamishwillee** [comment] 2023-09-13 03:02
Yes, fix by @rotu was merged. I have just merged this into the upstream mavlink/mavlink branch: https://github.com/mavlink/mavlink/pull/2038

**Closed by hamishwillee** 2023-09-13 03:02 UTC
